[project]
name = "114-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "fastapi[standard]>=0.123.4",
    "python-jose>=3.5.0"
]

[tool.uv.workspace]
members = [
    "python",
]
